// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rag} from '../models';
import {screen} from '../models';
import {config} from '../models';

export function AddRAGQA(arg1:string,arg2:string,arg3:string):Promise<rag.QAEntry>;

export function CancelRunningTask():Promise<boolean>;

export function CaptureExamQuestion():Promise<string>;

export function CheckMicrophoneAccess():Promise<number>;

export function CheckScreenCapturePermission():Promise<boolean>;

export function ClearResume():Promise<void>;

export function ClearScreenshots():Promise<void>;

export function CopyCode():Promise<void>;

export function DeleteRAGDocument(arg1:number):Promise<void>;

export function DeleteRAGQA(arg1:number):Promise<void>;

export function EmitEvent(arg1:string,arg2:Array<any>):Promise<void>;

export function GetInitStatus():Promise<string>;

export function GetModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetRAGKnowledge(arg1:string):Promise<rag.Snapshot>;

export function GetRegisteredTools():Promise<Array<string>>;

export function GetResumePDF():Promise<string>;

export function GetSTTModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetScreenshotPreview(arg1:number,arg2:number,arg3:boolean,arg4:boolean,arg5:string):Promise<screen.PreviewResult>;

export function GetSettings():Promise<config.Config>;

export function ImportRAGFiles(arg1:string):Promise<Array<rag.ImportResult>>;

export function IsInterruptThinkingEnabled():Promise<boolean>;

export function MoveWindow(arg1:number,arg2:number):Promise<void>;

export function OpenMicrophoneSettings():Promise<void>;

export function OpenScreenCaptureSettings():Promise<void>;

export function ParseResume():Promise<string>;

export function RebuildRAGIndex(arg1:string):Promise<rag.IndexResult>;

export function RemoveFocus():Promise<void>;

export function RemoveLastScreenshot():Promise<void>;

export function RemoveScreenshot(arg1:number):Promise<void>;

export function RequestMicrophoneAccess():Promise<void>;

export function RequestScreenCapturePermission():Promise<boolean>;

export function RestoreFocus():Promise<void>;

export function SaveImageToFile(arg1:string):Promise<boolean>;

export function ScrollContent(arg1:string):Promise<void>;

export function SelectResume():Promise<string>;

export function SetWindowAlwaysOnTop(arg1:boolean):Promise<void>;

export function StartLiveSession():Promise<void>;

export function StartRecordingKey(arg1:string):Promise<void>;

export function StopLiveSession():Promise<void>;

export function StopRecordingKey():Promise<void>;

export function SyncSettingsToDefaultSettings(arg1:string):Promise<string>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestRAGEmbedding(arg1:string):Promise<string>;

export function TestRAGSearch(arg1:string,arg2:string):Promise<rag.SearchTestResult>;

export function TestRealtimeConnection(arg1:string):Promise<string>;

export function ToggleClickThrough():Promise<void>;

export function ToggleVisibility():Promise<void>;

export function TriggerScreenshot():Promise<void>;

export function TriggerSend():Promise<void>;

export function TriggerSolve():Promise<void>;

export function UpdateRAGQA(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateSettings(arg1:string):Promise<string>;
