// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRAGQA(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRAGQA'](arg1, arg2, arg3);
}

export function CancelRunningTask() {
  return window['go']['main']['App']['CancelRunningTask']();
}

export function CaptureExamQuestion() {
  return window['go']['main']['App']['CaptureExamQuestion']();
}

export function CheckMicrophoneAccess() {
  return window['go']['main']['App']['CheckMicrophoneAccess']();
}

export function CheckScreenCapturePermission() {
  return window['go']['main']['App']['CheckScreenCapturePermission']();
}

export function ClearResume() {
  return window['go']['main']['App']['ClearResume']();
}

export function ClearScreenshots() {
  return window['go']['main']['App']['ClearScreenshots']();
}

export function CopyCode() {
  return window['go']['main']['App']['CopyCode']();
}

export function DeleteRAGDocument(arg1) {
  return window['go']['main']['App']['DeleteRAGDocument'](arg1);
}

export function DeleteRAGQA(arg1) {
  return window['go']['main']['App']['DeleteRAGQA'](arg1);
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function GetInitStatus() {
  return window['go']['main']['App']['GetInitStatus']();
}

export function GetModels(arg1, arg2) {
  return window['go']['main']['App']['GetModels'](arg1, arg2);
}

export function GetRAGKnowledge(arg1) {
  return window['go']['main']['App']['GetRAGKnowledge'](arg1);
}

export function GetRegisteredTools() {
  return window['go']['main']['App']['GetRegisteredTools']();
}

export function GetResumePDF() {
  return window['go']['main']['App']['GetResumePDF']();
}

export function GetSTTModels(arg1, arg2) {
  return window['go']['main']['App']['GetSTTModels'](arg1, arg2);
}

export function GetScreenshotPreview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetScreenshotPreview'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportRAGFiles(arg1) {
  return window['go']['main']['App']['ImportRAGFiles'](arg1);
}

export function IsInterruptThinkingEnabled() {
  return window['go']['main']['App']['IsInterruptThinkingEnabled']();
}

export function MoveWindow(arg1, arg2) {
  return window['go']['main']['App']['MoveWindow'](arg1, arg2);
}

export function OpenMicrophoneSettings() {
  return window['go']['main']['App']['OpenMicrophoneSettings']();
}

export function OpenScreenCaptureSettings() {
  return window['go']['main']['App']['OpenScreenCaptureSettings']();
}

export function ParseResume() {
  return window['go']['main']['App']['ParseResume']();
}

export function RebuildRAGIndex(arg1) {
  return window['go']['main']['App']['RebuildRAGIndex'](arg1);
}

export function RemoveFocus() {
  return window['go']['main']['App']['RemoveFocus']();
}

export function RemoveLastScreenshot() {
  return window['go']['main']['App']['RemoveLastScreenshot']();
}

export function RemoveScreenshot(arg1) {
  return window['go']['main']['App']['RemoveScreenshot'](arg1);
}

export function RequestMicrophoneAccess() {
  return window['go']['main']['App']['RequestMicrophoneAccess']();
}

export function RequestScreenCapturePermission() {
  return window['go']['main']['App']['RequestScreenCapturePermission']();
}

export function RestoreFocus() {
  return window['go']['main']['App']['RestoreFocus']();
}

export function SaveImageToFile(arg1) {
  return window['go']['main']['App']['SaveImageToFile'](arg1);
}

export function ScrollContent(arg1) {
  return window['go']['main']['App']['ScrollContent'](arg1);
}

export function SelectResume() {
  return window['go']['main']['App']['SelectResume']();
}

export function SetWindowAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetWindowAlwaysOnTop'](arg1);
}

export function StartLiveSession() {
  return window['go']['main']['App']['StartLiveSession']();
}

export function StartRecordingKey(arg1) {
  return window['go']['main']['App']['StartRecordingKey'](arg1);
}

export function StopLiveSession() {
  return window['go']['main']['App']['StopLiveSession']();
}

export function StopRecordingKey() {
  return window['go']['main']['App']['StopRecordingKey']();
}

export function SyncSettingsToDefaultSettings(arg1) {
  return window['go']['main']['App']['SyncSettingsToDefaultSettings'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function TestRAGEmbedding(arg1) {
  return window['go']['main']['App']['TestRAGEmbedding'](arg1);
}

export function TestRAGSearch(arg1, arg2) {
  return window['go']['main']['App']['TestRAGSearch'](arg1, arg2);
}

export function TestRealtimeConnection(arg1) {
  return window['go']['main']['App']['TestRealtimeConnection'](arg1);
}

export function ToggleClickThrough() {
  return window['go']['main']['App']['ToggleClickThrough']();
}

export function ToggleVisibility() {
  return window['go']['main']['App']['ToggleVisibility']();
}

export function TriggerScreenshot() {
  return window['go']['main']['App']['TriggerScreenshot']();
}

export function TriggerSend() {
  return window['go']['main']['App']['TriggerSend']();
}

export function TriggerSolve() {
  return window['go']['main']['App']['TriggerSolve']();
}

export function UpdateRAGQA(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateRAGQA'](arg1, arg2, arg3, arg4);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
